### ISSUE TITLE
用模拟器会有问题

### ISSUE THREAD

**Issue by 5A59** [linroid/sadb#11]
模拟器 devices 输出:
emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86
报错：
Traceback (most recent call last):
  File "/usr/local/bin/sadb", line 11, in <module>
    sys.exit(sadb())
  File "/usr/local/lib/python2.7/site-packages/sadb/__init__.py", line 23, in sadb
    devices, outputs = read_devices()
  File "/usr/local/lib/python2.7/site-packages/sadb/__init__.py", line 96, in read_devices
    'device': d[5]
IndexError: list index out of range

**Comment by xlzd** [comment]
@linroid

**Comment by linroid** [comment]
不好意思才看到，已经修复 https://github.com/linroid/sadb/commit/0e2cd2adc30f613e81caa40b20afd5578db3ff6a ，执行以下命令更新：
`pip install sadb --upgrade`
