### ISSUE TITLE
TypeError: expected string or buffer

### ISSUE THREAD

**Issue by kaiziwangzi** [linroid/sadb#2]
嗨，当我选择设备安装的时候遇到了这个问题
➜  debug git:(xxx) ✗ adb install facedemo-debug.apk 
Device list:
0) All devices
1) 1795826      transport_id:5
2) 0123abcd     transport_id:4

select: 1
Traceback (most recent call last):
  File "/usr/local/bin/sadb", line 9, in <module>
    load_entry_point('sadb==0.0.2', 'console_scripts', 'sadb')()
  File "/Library/Python/2.7/site-packages/sadb/__init__.py", line 33, in sadb
    nums = select_devices(devices)
  File "/Library/Python/2.7/site-packages/sadb/__init__.py", line 51, in select_devices
    splits = re.split(r'[\s+,]', str)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 171, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or buffer

**Comment by kaiziwangzi** [comment]
改了一下源码，抱歉~
__init__.py
第50行
str = input("\nselect: ")  ->  str = raw_input("\nselect: ")

**Comment by linroid** [comment]
python2兼容问题~

已解决 #4

**Comment by kaiziwangzi** [comment]
enen~速度杠杠的，已更新
