### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by yunxu-it** [linroid/sadb#7]
单个设备
使用命令 `sadb devices`
以下错误：
```shell
$ sadb devices
Traceback (most recent call last):
  File "E:\Lang\Python36\Scripts\sadb-script.py", line 11, in <module>
    load_entry_point('sadb==0.0.4', 'console_scripts', 'sadb')()
  File "e:\lang\python36\lib\site-packages\sadb\__init__.py", line 22, in sadb
    devices, outputs = read_devices()
  File "e:\lang\python36\lib\site-packages\sadb\__init__.py", line 96, in read_devices
    'transport_id': d[6]
IndexError: list index out of range
```
使用`adb devices`，正常

**Comment by linroid** [comment]
可以把执行`adb devices`的完整输出贴下吗？

**Comment by yunxu-it** [comment]
```
$ adb devices
List of devices attached
0786eff80c9298e0        device
```

**Comment by linroid** [comment]
抱歉。。需要 `adb devices -l` 的结果，麻烦重新贴下:)

**Comment by yunxu-it** [comment]
```
$ adb devices -l
List of devices attached
0786eff80c9298e0       device product:hammerhead model:Nexus_5 device:hammerhead
```

**Comment by linroid** [comment]
已解决，可以执行以下命令更新下，谢谢支持~
```bash
pip install sadb --upgrade
```

**Comment by xingstarx** [comment]
在真机下正常，在模拟器下使用报错
```shell
➜  ~ sadb devices
Traceback (most recent call last):
  File "/usr/local/bin/sadb", line 11, in <module>
    sys.exit(sadb())
  File "/usr/local/lib/python3.6/site-packages/sadb/__init__.py", line 23, in sadb
    devices, outputs = read_devices()
  File "/usr/local/lib/python3.6/site-packages/sadb/__init__.py", line 96, in read_devices
    'device': d[5]
IndexError: list index out of range
```
使用adb devices的结果如下：
```shell
➜  ~ adb devices
List of devices attached
192.168.57.101:5555	device
```
希望能解决下，谢谢啦
